[[custom_groups]]
name = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
rule = ["â™»ï¸ è‡ªåŠ¨é€‰æ‹©", "ğŸ¯ å…¨çƒç›´è¿", ".*"]
type = "select"

[[custom_groups]]
interval = 300
name = "â™»ï¸ è‡ªåŠ¨é€‰æ‹©"
rule = [".*"]
type = "url-test"
url = "http://www.gstatic.com/generate_204"

[[custom_groups]]
name = "ğŸ¥ NETFLIX"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ“¹ Youtube"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ¤– Openai"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ“² Telegram"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ“º Bilibili"
rule = [
  "ğŸ¯ å…¨çƒç›´è¿",
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  ".*",
]
type = "select"

[[custom_groups]]
name = "â“‚ï¸ å¾®è½¯æœåŠ¡"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ®ï¸ æ¸¸æˆå¹³å°"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ è‹¹æœæœåŠ¡"
rule = [
  "ğŸ¯ å…¨çƒç›´è¿",
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸŒ å›½å¤–åª’ä½“"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"

[[custom_groups]]
name = "ğŸ‡¨ğŸ‡³ å›½å†…åª’ä½“"
rule = [
  "ğŸ¯ å…¨çƒç›´è¿",
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  ".*",
]
type = "select"

[[custom_groups]]
name = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
rule = ["REJECT", "DIRECT"]
type = "select"

[[custom_groups]]
name = "ğŸ¯ å…¨çƒç›´è¿"
rule = ["DIRECT"]
type = "select"

[[custom_groups]]
name = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
rule = [
  "ğŸ”° èŠ‚ç‚¹é€‰æ‹©",
  "ğŸ¯ å…¨çƒç›´è¿",
  ".*",
]
type = "select"
