# é å‰çš„è§„åˆ™ä¼šè¦†ç›–é åçš„è§„åˆ™

# ========= å®šåˆ¶è§„åˆ™ï¼Œæœ€é«˜ä¼˜å…ˆ =========

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/custom/Direct.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/custom/Global.list"

# ========= å¹¿å‘Šæ‹¦æˆª =========

[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/ACL4SSR/Clash/BanAD.list"

[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/ACL4SSR/Clash/BanEasyListChina.list"

[[rulesets]]
group = "â›”ï¸ å¹¿å‘Šæ‹¦æˆª"
ruleset = "rules/ACL4SSR/Clash/BanProgramAD.list"

# ========= å›½å†…æœåŠ¡æœ‰æœåŠ¡ä¸”æ— è§†åç»­æŒ‡å®š =========

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/LocalAreaNetwork.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/UnBan.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/GoogleCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/SteamCN.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Ruleset/SteamRegionCheck.list"

# ========= å›½å†…æœ‰æœåŠ¡ï¼Œä½†æ˜¯éœ€è¦å•ç‹¬æŒ‡å®š =========

[[rulesets]]
group = "â“‚ï¸ å¾®è½¯æœåŠ¡"
ruleset = "rules/ACL4SSR/Clash/Microsoft.list"

[[rulesets]]
group = "ğŸ“º Bilibili"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Bilibili.list"

[[rulesets]]
group = "ğŸ“º Bilibili"
ruleset = "rules/ACL4SSR/Clash/Ruleset/BilibiliHMT.list"

[[rulesets]]
group = "ğŸ®ï¸ æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Steam.list"

[[rulesets]]
group = "ğŸ®ï¸ æ¸¸æˆå¹³å°"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Epic.list"

[[rulesets]]
group = "ğŸ è‹¹æœæœåŠ¡"
ruleset = "rules/ACL4SSR/Clash/Apple.list"

# ========= å›½å†…æœ‰æœåŠ¡ =========

[[rulesets]]
group = "ğŸ‡¨ğŸ‡³ å›½å†…åª’ä½“"
ruleset = "rules/ACL4SSR/Clash/ChinaMedia.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/ChinaDomain.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/ChinaCompanyIp.list"

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "rules/ACL4SSR/Clash/Download.list"

# ========= å›½å†…æ— æœåŠ¡ =========

[[rulesets]]
group = "ğŸ¥ NETFLIX"
ruleset = "rules/ACL4SSR/Clash/Netflix.list"

[[rulesets]]
group = "ğŸ“¹ Youtube"
ruleset = "rules/ACL4SSR/Clash/Ruleset/YouTube.list"

[[rulesets]]
group = "ğŸ“² Telegram"
ruleset = "rules/ACL4SSR/Clash/Ruleset/Telegram.list"

[[rulesets]]
group = "ğŸ¤– Openai"
ruleset = "rules/ACL4SSR/Clash/Ruleset/OpenAi.list"

[[rulesets]]
group = "ğŸŒ å›½å¤–åª’ä½“"
ruleset = "rules/ACL4SSR/Clash/ProxyMedia.list"

[[rulesets]]
group = "ğŸ”° èŠ‚ç‚¹é€‰æ‹©"
ruleset = "rules/ACL4SSR/Clash/ProxyGFWlist.list"

# # ========= FALLBACK =========

[[rulesets]]
group = "ğŸ¯ å…¨çƒç›´è¿"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "ğŸŸ æ¼ç½‘ä¹‹é±¼"
ruleset = "[]FINAL"
